[package]
name = "spacehub"
version = "0.1.0"
authors = ["MTRNord <mtrnord1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matrix-sdk = "0.2"
tokio = {version = "0.2", features = ["full"]}
color-eyre = "0.5"
async-trait = "0.1.41"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2.4"

